### ISSUE TITLE
User cancelled hostkey check on Azure DevOps

### ISSUE THREAD

**Issue by containerpope** [fluxcd/image-automation-controller#106]
Currently the imageautomationupdate I created is failing with the error: ** error: user cancelled hostkey check**

The system is setup as follows:

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: base-backend-repo
  namespace: tenant-backend
spec:
  interval: 2m0s
  ref:
    branch: main
  url: ssh://XXX@vs-ssh.visualstudio.com/v3/XXX/XXX/XXX
  gitImplementation: libgit2 # Special for azure devops
  secretRef:
    name: ssh-credentials
  ignore: |
    .git/
    .github/
    scripts/
```

```yaml
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: tenant-backend-image-update
  namespace: tenant-backend
spec:
  checkout:
    branch: main
    gitRepositoryRef:
      name: base-backend-repo
  commit:
    authorEmail: fluxcdbot@flux.com
    authorName: fluxcdbot
    messageTemplate: '[ci skip] update image'
  interval: 1m0s
  update:
    strategy: Setters
```

This results in the following:

```sh
│   Conditions:                                                                                                                                                                                                                                                                                                                                                  │
│     Last Transition Time:  2021-02-05T17:27:30Z                                                                                                                                                                                                                                                                                                                │
│     Message:               unable to clone 'ssh://XXX@vs-ssh.visualstudio.com/v3/XXX/XXX/XXX', error: user cancelled hostkey check                                                                                                                                                                                                │
│     Reason:                ReconciliationFailed                                                                                                                                                                                                                                                                                                                │
│     Status:                False                                                                                                                                                                                                                                                                                                                               │
│     Type:                  Ready                                                                                                                                                                                                                                                                                                                               │
│   Observed Generation:     1                                                                                                                                                                                                                                                                                                                                   │
│ Events:                                                                                                                                                                                                                                                                                                                                                        │
│   Type    Reason  Age                      From                         Message                                                                                                                                                                                                                                                                                │
│   ----    ------  ----                     ----                         -------                                                                                                                                                                                                                                                                                │
│   Normal  error   4m21s (x334 over 3d15h)  image-automation-controller  unable to clone 'ssh://XXX@vs-ssh.visualstudio.com/v3/XXX/XXX/XXX', error: user cancelled hostkey check
```

The ssh credentials are correct, because all other processes are working as expected, so there seems to be only an issue in the image update controller.
