### ISSUE TITLE
Image markers are not usable with configuration transpilers 

### ISSUE THREAD

**Issue by toddkazakov** [fluxcd/image-automation-controller#134]
Image markers cannot be emitted by configuration transpilers like jsonnet, because they are comments in yaml files. In our case this makes the migration from flux v1 nearly impossible, because we'll have to completely rewrite our entire infrastructure configuration. 

It would be great to have support for additional way of defining image markers as data in the yaml file, ideally as flux v1 annotations.

**Comment by stefanprodan** [comment]
@toddkazakov do you generate with jsonnet the Flux custom resources like GitRepository/Kustomization/ImagePolicy/etc or these YAMLs are generated with flux CLI?

**Comment by toddkazakov** [comment]
Currently, we're only exploring the migration path, but ideally we'd like to be able to use jsonnet for generating all yaml files, including the flux custom resources.

**Comment by stefanprodan** [comment]
Can you place a YAML file next to jsonnet and use the values from that file when generating the manifests? If so then you could create a config file like so:

```yaml
apiVersion: my.config.k8s.io/v1
kind: MyImages
images:
 - app1: init-tag # {"$imagepolicy": "apps-ns:app1:tag"}
 - app2: init-tag # {"$imagepolicy": "apps-ns:app2:tag"}
```

Flux will update the config file, then you'll generate the manifests using the tags from the config.
