### ISSUE TITLE
Empty commits

### ISSUE THREAD

**Issue by PaulRudin** [fluxcd/image-automation-controller#135]
I have an ImageUpdateAutomation object with spec.interval set to 1m0s. I see a new commit to my repo every minute, whether or not any image has changed, so the vast majority of these commits are empty commits (i.e. no changes).

The empty commits are, I suppose, harmless; but it would be nice if there was a way of avoiding them.

**Comment by squaremo** [comment]
In the normal course of things, I would expect the controller to skip an update when there are no changes made. Are you using the new "push branch" part of the API?

```yaml
  push:
    branch: <something>
```

Can I see the ImageUpdateAutomation definition, perhaps?

**Comment by PaulRudin** [comment]
I don't think I'm using the "push branch" thing... here's the definition:
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/PaulRudin/xamaral
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  checkout:
    branch: main
    gitRepositoryRef:
      name: flux-system
  commit:
    authorEmail: fluxcdbot@users.noreply.github.com
    authorName: fluxcdbot
    messageTemplate: '[ci skip] update image'
  interval: 1m0s
  update:
    strategy: Setters
```
