### ISSUE TITLE
Reconcilation error when pushing to different branch

### ISSUE THREAD

**Issue by punycode** [fluxcd/image-automation-controller#138]
While trying the `spec.push.branch` feature of `ImageUpdateAutomation`, I found that the reconcilation of the object was failing after it initially pushed a commit. I updated an image in my repository and triggered the reconcilation:

```sh
$ flux reconcile image update flux-system
► annotating ImageUpdateAutomation flux-system in flux-system namespace
✔ ImageUpdateAutomation annotated
◎ waiting for ImageUpdateAutomation reconciliation
✔ ImageUpdateAutomation reconciliation completed
✔ committed and pushed 45a4c402516dd0c0b1bfde5a3b6a5c85684ddc1e to updates/test
$ flux get image update
NAME       	READY	MESSAGE         	LAST RUN                 	SUSPENDED 
flux-system	False	object not found	2021-03-26T15:48:45+01:00	False    	
```

Also, when then pushing another image version, reconcilation always fails and doesn't even produce another commit:

```
$ flux reconcile image update flux-system
► annotating ImageUpdateAutomation flux-system in flux-system namespace
✔ ImageUpdateAutomation annotated
◎ waiting for ImageUpdateAutomation reconciliation
✔ ImageUpdateAutomation reconciliation completed
✗ ImageUpdateAutomation reconciliation failed
```

The flux version I am using is `0.10.0` with `image-automation-controller:v0.7.0`. This here is the (shortened) `ImageUpdateAutomation`:

```yaml
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  checkout:
    branch: flux-v2-migrate
    gitRepositoryRef:
      name: flux-system
  commit:
    authorEmail: noreply@example.com
    authorName: FluxCD
  interval: 5m0s
  push:
    branch: updates/test
  update:
    path: ./clusters/test
    strategy: Setters
```
