### ISSUE TITLE
unknown field "signingKey" in "image.toolkit.fluxcd.io/v1alpha1"

### ISSUE THREAD

**Issue by fajarhide** [fluxcd/image-automation-controller#148]
``
validation failed: error: error validating "434f9a23-458c-461c-a5ec-589cac17eaa0.yaml": error validating data: ValidationError(ImageUpdateAutomation.spec.commit): unknown field "signingKey" in io.fluxcd.toolkit.image.v1alpha1.ImageUpdateAutomation.spec.commit; if you choose to ignore these errors, turn validation off with --validate=false
``

from documentation https://toolkit.fluxcd.io/components/image/imageupdateautomations/#commit

I define it according to this for my private repo
```
spec:
  commit:
    authorName: Fluxbot
    authorEmail: flux@example.com
    signingKey:
      secretRef:
        name: gpg-private-key
```

any version other than that `v1alpha1` ?

**Comment by hiddeco** [comment]
This is available since `0.8.0` but requires an update to the Custom Resource Definition in your cluster, please confirm it matches: https://github.com/fluxcd/image-automation-controller/blob/a4f5b8f38a962994ff59ce988667c16f024b5f7e/config/crd/bases/image.toolkit.fluxcd.io_imageupdateautomations.yaml#L83-L99

**Comment by fajarhide** [comment]
>>This is available since `0.8.0` but requires an update to the Custom Resource Definition in your cluster, please confirm it matches:
>> 
>> https://github.com/fluxcd/image-automation-controller/blob/a4f5b8f38a962994ff59ce988667c16f024b5f7e/config/crd/bases/image.toolkit.fluxcd.io_imageupdateautomations.yaml#L83-L99



ok thanks, btw how to run this image automation update? 
why that there is no trigger to github commit to update the image tag, even though the image policy found the latest image tag ?

flux should automatically update the image tag of `0161318406fce71d7523499d294be8aba2735a0a` to `staging-225b41707a552878059ccaa0ac90fce15402549d-1618203885` right ?

cc: @stefanprodan

### log imageautomationupdate pod
```
{"level":"info","ts":"2021-04-13T09:21:22.012Z","logger":"controller-runtime.manager.controller.imageupdateautomation","msg":"Starting workers","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","worker count":1}
```

### my image policy found images tag latest
```
>> k get imagepolicies.image.toolkit.fluxcd.io -A
NAMESPACE   NAME                    LATESTIMAGE
staging     be-service              registry.com/tech/service:staging-225b41707a552878059ccaa0ac90fce15402549d-1618203885
```
### the file that I want to update when I find the latest tag from the image policy
```
>> cat ./apps/staging/service/patch.yaml | grep "tag"
      tag: 0161318406fce71d7523499d294be8aba2735a0a # {"$imagepolicy": "staging:be-service:tag"}
```
ref: https://toolkit.fluxcd.io/guides/image-update/#configure-image-update-for-custom-resources

### my config imageupdateautomation
```
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: flux-system-staging
  namespace: flux-system
spec:
  checkout:
    branch: main
    gitRepositoryRef:
      name: flux-system
  commit:
    authorEmail: fluxcdbot@example.com
    authorName: fluxcdbot
    signingKey:
      secretRef:
        name: flux-system
    messageTemplate: |
      Automated image update:
      {{ range .Updated.Images -}}
      - {{.}}
      {{ end -}}
  interval: 1m0s
  push:
    branch: main
  update:
    path: ./apps/staging
    strategy: Setters
```
my repository flux on the branch `main`
