### ISSUE TITLE
Policy doesn't see newer tags after upgrade to 0.12

### ISSUE THREAD

**Issue by oliver-kriska** [fluxcd/image-automation-controller#149]
Hello,

after I upgraded flux to 0.12.0 and later to 0.12.1 there were some issues. It creates a lot errors and after couple of days I figured out that doesn't update all deployments because policy doesn't see the latest tags. See logs and commands outputs. I upgraded flux last week and I thought it works but I figured out that the latest upgrade was this morning. We have pushed image tags after that and it didn't apply them. So it's weird because looks like it works just sometimes. 

```bash
flux -v
flux version 0.12.1

flux check
► checking prerequisites
✔ kubectl 1.21.0 >=1.18.0-0
✔ Kubernetes 1.19.9+IKS >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.9.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.8.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.8.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.11.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.12.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.11.0
✔ all checks passed

flux -n test get image repository merchant
NAME    	READY	MESSAGE                         	LAST SCAN                	SUSPENDED
merchant	True 	successful scan, found 1896 tags	2021-04-13T14:42:45+02:00	False

flux -n test get image policy merchant
NAME    	READY	MESSAGE                  	LATEST IMAGE
merchant	False	no image found for policy

```

My configs:
```yaml
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: update-automation
  namespace: test
spec:
  checkout:
    branch: master
    gitRepositoryRef:
      name: flux-system
  commit:
    authorEmail: tech@payout.one
    authorName: fluxcdbot
    messageTemplate: '[ci skip] update image'
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: merchant
  namespace: test
spec:
  imageRepositoryRef:
    name: merchant
  policy:
    semver:
      range: 1.2.x
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: merchant
  namespace: test
spec:
  image: blabalba/merchant
  interval: 3m0s
  secretRef:
    name: blabalba
```

I got plenty of these errors:

```
Apr 12 14:57:40 image-automation-controller-6d9cf88649-28n5h manager error 
{
    "error": "POST http://notification-controller/ giving up after 5 attempt(s)",
    "level": "error",
    "logger": "controller-runtime.manager.controller.imageupdateautomation",
    "msg": "unable to send event",
    "name": "update-automation",
    "namespace": "test",
    "reconciler group": "image.toolkit.fluxcd.io",
    "reconciler kind": "ImageUpdateAutomation",
    "ts": "2021-04-12T12:57:40.613Z"
}

.....

{
    "level": "info",
    "logger": "event-server",
    "msg": "Discarding event, no alerts found for the involved object",
    "name": "merchant",
    "namespace": "test",
    "reconciler kind": "ImagePolicy",
    "ts": "2021-04-12T13:08:32.421Z"
}

```

After I downgrade to version 0.11.0 it works without any issue:
```bash
./flux -v
flux version 0.11.0

./flux check
► checking prerequisites
✗ flux 0.11.0 <0.12.2 (new version is available, please upgrade)
✔ kubectl 1.21.0 >=1.18.0-0
✔ Kubernetes 1.19.9+IKS >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.9.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.7.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.7.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.10.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.11.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.10.0
✔ all checks passed
```
Let me know if you want need some more information or test something.
