### ISSUE TITLE
Image update automation not committing the resolved version to git 

### ISSUE THREAD

**Issue by sanjvij** [fluxcd/image-automation-controller#159]
Hi team,

Thanks for your help so far. I am stuck at implementing a use case where by the image update automation policy is not applying the changes to the git. 

When I run the command as below, I can see that flux was able to detect a new version in the registry but never committed the same to git. 
**(base) sanj@Sanjs-Air app-cluster % flux get image policy staging**
NAME   	READY	MESSAGE                                                             	LATEST IMAGE                     
staging	True 	Latest image tag for 'sanjvij01/getting-started' resolved to: v3.0.2	sanjvij01/getting-started:v3.0.2

**(base) sanj@Sanjs-Air app-cluster % kubectl get deployment/getting-started-image -n staging -oyaml | grep 'image'**
  name: getting-started-image
  selfLink: /apis/apps/v1/namespaces/staging/deployments/getting-started-image
      - image: sanjvij01/getting-started:v3.0.1
        imagePullPolicy: IfNotPresent
    message: ReplicaSet "getting-started-image-554964548d" has successfully progressed.

my image update automation file looks like below. I have a feeling I have done something in which case feel free to point. 
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  checkout:
    branch: master
    gitRepositoryRef:
      name: flux-staging
  commit:
    authorEmail: sanjvij01@gmail.com
    authorName: sanjvij
    messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
  interval: 1m0s
  push:
    branch: master
  update:
    path: ./
    strategy: Setters

Let me know if you need me to provide any further info.

**Comment by rayterrill** [comment]
Downgraded cluster to v0.11.0, still not able to get image-automation-controller working correctly, and not sure where to start looking to understand why it isn't making an update.

**Comment by rayterrill** [comment]
Update - Dug into the manifests for the flux components - looks like we can put the image-automation-controller in debug mode:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/version: v0.11.0
    control-plane: controller
  name: image-automation-controller
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-automation-controller
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: image-automation-controller
    spec:
      containers:
      - args:
        - --events-addr=http://notification-controller/
        - --watch-all-namespaces=true
        - --log-level=debug
        - --log-encoding=json
        - --enable-leader-election
```
