### ISSUE TITLE
Bug with commit in custom branch

### ISSUE THREAD

**Issue by yuriydzobak** [fluxcd/image-automation-controller#161]
Hi
Does anybody face an issue with ImageUpdateAutomation when you use `update.path`
I’ve enabled `update.path`  and contoller has create a custom branch with changes in custom path, but sometimes, the contoller pushed commit that modify only tag under `update.path` but sometimes it pushed commit that modify `tag` and remove all files that wasn’t included in `update.path`
for example, first and second  commit modify files in `env/cluster` and doesn’t touch any other files in `/*`  but sometimes it modify file in `env/cluster`  and remove other files from `/*`

<img width="1447" alt="image" src="https://user-images.githubusercontent.com/70581130/117124626-41c98d80-ada1-11eb-9120-3eb5acaf5541.png">

Also, it happed in different flux contollers
I have deployed flux in two clusters and that issue show up

```
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: image-update-automation
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: github
  git:
    checkout:
      ref:
        branch: master
    push:
      branch: flux-image-update-cluster1
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        [ci-skip] Automated image update

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Updated.Files -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $_ := .Updated.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
        {{ end -}}

        Images:
        {{ range .Updated.Images -}}
        - {{.}}
        {{ end -}}
  update:
    strategy: Setters
    path: "env/cluster1"
```

I upgrade the controller to latest version(v0.9.0), but it didn't help
