### ISSUE TITLE
Empty commits

### ISSUE THREAD

**Issue by Nicklason** [fluxcd/image-automation-controller#166]
I am using the ImageUpdateAutomation resource and see empty commits being pushed to my git repository. I looked at a similiar issue (#135) but they got an empty commit every minute, where I get them randomly, so I believe it is a different issue.

I have had the issue since 20. april. I was using flux v0.12.1 back then, and now I use latest version v0.13.4 and I still get them.

20/4/2021
![image](https://user-images.githubusercontent.com/21038945/118412556-f8c7e200-b69a-11eb-9b3f-46d851ddf243.png)

16/5/2021
![image](https://user-images.githubusercontent.com/21038945/118412573-07ae9480-b69b-11eb-9e43-564d54cb8c5c.png)

```yaml
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: 'update manifests'
  interval: 1m0s
```

**Comment by squaremo** [comment]
Any chance I can see the git repo you're using? I understand if it contains sensitive data and you'd prefer not. You might have to help me out with narrowing down where the problem happens ..

**Comment by Nicklason** [comment]
The git repository is a private GitHub repository but I can share it with you. I would prefer to mail you a zip file but I guess I could just add you as a contributor.

**Comment by squaremo** [comment]
> I would prefer to mail you a zip file but I guess I could just add you as a contributor.

Either works for me -- you can email a zip to the address on my profile, or michael@weave.works.

**Comment by chicken231** [comment]
I'm having this same problem as well. Same behavior on Flux2 `v0.13.4` and `v0.14.2`.

I haven't built or put a new image in this AWS ECR repo since last week. I just updated to Flux's latest and reapplied my kustomization to continue testing today.
My image automation intervals are set to every 2m, so it seems that at each time of reconciliation, it's making a commit at that interval even if it's empty/unneeded because there's no update to the image tag.
I'm using BitBucket.

My Kustomization:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: www-test-eks-com-v1
  namespace: backend
spec:
  images:
  - name: 000000000000.dkr.ecr.us-east-1.amazonaws.com/www-test-eks-com-v1
    newTag: 20210527-223554 # {"$imagepolicy": "flux-system:www-test-eks-com-v1:tag"}
  interval: 10m0s
  path: ./flux/kustomize/apps/www-test-eks-com-v1
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: www-test-eks-com-v1
    namespace: backend
  timeout: 2m
```

Excerpt from the relevant `deployment.yaml`:
```yml
      containers:
      - name: www-test-eks-com-v1
        image: 000000000000.dkr.ecr.us-east-1.amazonaws.com/www-test-eks-com-v1:20210505-233849
```

Image Automation objects:
```yml
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: www-test-eks-com-v1
  namespace: flux-system
spec:
  git:
    commit:
      messageTemplate: |
        Automated image update

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Updated.Files -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $_ := .Updated.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
        {{ end -}}

        Images:
        {{ range .Updated.Images -}}
        - {{.}}
        {{ end -}}
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    # namespace: flux-system
  suspend: false
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: www-test-eks-com-v1
  namespace: flux-system
spec:
  image: 000000000000.dkr.ecr.us-east-1.amazonaws.com/www-test-eks-com-v1
  interval: 2m0s
  secretRef:
    name: ecr-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: www-test-eks-com-v1
  namespace: flux-system
spec:
  filterTags:
    pattern: '((?P<timestamp>\d{8}-\d{6})|(?P<timestamp>\d{8}-\d{6}-\d{1}))'
    extract: '$timestamp'
  imageRepositoryRef:
    name: www-test-eks-com-v1
  policy:
    alphabetical:
      order: asc
```

Flux CLI output concerning images:
```
❯ flux get images all
NAME                                    READY   MESSAGE                         LAST SCAN                       SUSPENDED
imagerepository/www-test-eks-com-v1     True    successful scan, found 3 tags   2021-06-03T13:00:30-07:00       False

NAME                            READY   MESSAGE                                                                                                                         LATEST IMAGE
imagepolicy/www-test-eks-com-v1 True    Latest image tag for '000000000000.dkr.ecr.us-east-1.amazonaws.com/www-test-eks-com-v1' resolved to: 20210527-223554   000000000000.dkr.ecr.us-east-1.amazonaws.com/www-test-eks-com-v1:20210527-223554

NAME                                            READY   MESSAGE                                                                 LAST RUN                        SUSPENDED
imageupdateautomation/www-test-eks-com-v1       True    committed and pushed 6421cfd32363cac84bd70b6fa2a8e0a4402a7845 to master 2021-06-03T13:00:45-07:00       False
```

Logs - Image Automation Controller:
```json
{"level":"info","ts":"2021-06-03T19:51:44.079Z","logger":"controller-runtime.manager.controller.imageupdateautomation","msg":"Starting workers","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","worker count":1}
{"level":"info","ts":"2021-06-03T19:51:59.653Z","logger":"controller-runtime.manager.controller.imageupdateautomation","msg":"pushed commit to origin","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"www-test-eks-com-v1","namespace":"flux-system","revision":"fa68e0a261ad6aa9b8cb4ecc8db89cc68f07326f","branch":"master"}
{"level":"info","ts":"2021-06-03T19:52:08.908Z","logger":"controller-runtime.manager.controller.imageupdateautomation","msg":"pushed commit to origin","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"www-test-eks-com-v1","namespace":"flux-system","revision":"8e214093bf5e9870ea18319ff63032e000569296","branch":"master"}
{"level":"info","ts":"2021-06-03T19:54:12.551Z","logger":"controller-runtime.manager.controller.imageupdateautomation","msg":"pushed commit to origin","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"www-test-eks-com-v1","namespace":"flux-system","revision":"c8c8dbd510859b8c8202eef437841693d37b8641","branch":"master"}
{"level":"info","ts":"2021-06-03T19:56:24.110Z","logger":"controller-runtime.manager.controller.imageupdateautomation","msg":"pushed commit to origin","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"www-test-eks-com-v1","namespace":"flux-system","revision":"89e4da1fe3221f66222ff32af1120061ab7859bc","branch":"master"}
```

Events - Image Automation controller:
```
Events:
  Type    Reason  Age    From                         Message
  ----    ------  ----   ----                         -------
  Normal  info    15m    image-automation-controller  committed and pushed change 8b49c700a03b516d5796b267724a66d85b483d60 to master
  Normal  info    13m    image-automation-controller  committed and pushed change a98daef1c988002f452fa1e1c39986c7dd9310ca to master
  Normal  info    11m    image-automation-controller  committed and pushed change 41a74a71939bdb116a1682d757614d34b9d540ef to master
  Normal  info    9m4s   image-automation-controller  committed and pushed change fe2b439a906fc48b7771cbed71130fa0da253e18 to master
  Normal  info    8m1s   image-automation-controller  committed and pushed change efc761e63bd7544f81275bb8437f5cd47992518a to master
  Normal  info    7m13s  image-automation-controller  committed and pushed change d08486200e77261161d2d3eb44c07b0a19ce8e03 to master
  Normal  info    7m9s   image-automation-controller  committed and pushed change 1371b7876e1de0adb49e9581a44b5324e9f603dc to master
  Normal  info    7m3s   image-automation-controller  committed and pushed change 03cf55b6acc038d8a2b0fdb193138bac5399f49c to master
  Normal  info    6m1s   image-automation-controller  committed and pushed change fa68e0a261ad6aa9b8cb4ecc8db89cc68f07326f to master
  Normal  info    5m52s  image-automation-controller  committed and pushed change 8e214093bf5e9870ea18319ff63032e000569296 to master
  Normal  info    3m48s  image-automation-controller  committed and pushed change c8c8dbd510859b8c8202eef437841693d37b8641 to master
  Normal  info    96s    image-automation-controller  committed and pushed change 89e4da1fe3221f66222ff32af1120061ab7859bc to master
```

BitBucket's commit page:
![Screenshot_20210603_130338](https://user-images.githubusercontent.com/33075383/120705669-f9b78c80-c46c-11eb-88b1-9a52d40af483.png)
