### ISSUE TITLE
flux 0.14.1 empty git-upload-pack given

### ISSUE THREAD

**Issue by rayanebel** [fluxcd/image-automation-controller#172]
Hi everyone,

Today I've upgraded our flux instance to the latest version `0.14.1` and after migrating all our `ImageUpdateAutomation` resources to the new format according to this [documentation](https://github.com/fluxcd/flux2/discussions/1333), we have the following error message: `empty git-upload-pack given` which is unclear for us.

We are using Github and we have private repositories.

```bash
NAMESPACE  	NAME                                        	READY	MESSAGE                    	LAST RUN	SUSPENDED
flux-system	imageupdateautomation/advisors              	False	empty git-upload-pack given	        	False
flux-system	imageupdateautomation/client360             	False	empty git-upload-pack given	        	False
flux-system	imageupdateautomation/transactions          	False	empty git-upload-pack given	        	False
flux-system	imageupdateautomation/users                 	False	empty git-upload-pack given	        	False
```

You can find below the yaml of one of our `ImageUpdateAutomation` resource

```yaml
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: products
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: ../applications/apis/overlays/dev
    strategy: Setters
```

Can someone help us to understand what's going on and what's this error message means ?

Thanks.

**Comment by stefanprodan** [comment]
Can you post here the GitRepository manifest, the relevant part is the Git URL.

**Comment by rayanebel** [comment]
Hi @stefanprodan 

Here you can find the `flux-system` GitRepository manifest.

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  timeout: 20s
  url: https://github.com/xxxxxx/fred-gcp-gitops.git
```
