### ISSUE TITLE
images are not fetched

### ISSUE THREAD

**Issue by kadzielawa** [fluxcd/image-automation-controller#180]
Hello,
thank you for your powerful tool, I really like it! great job ! it's big milestone to gitops :) 
I have problem with fluxcd2 because during creating processes which would be automatically after pushing images to ECR repository, HelmRelease is not upgrading containers however ImageUpdateAutomation works great and helm values file is updated on git repository very well.

not upgrading containers - I mean that even in repository the image is in the newest version eg.(sdd9) container is still in wrong version...
do you have any ideas what it's wrong with those files?

flux logs doesn't return nothing special... I see only that every one minute updating working.

something like values.yaml are not valid recognize by kubernetes   


```
Every 2.0s: flux get images all                                                                                                                                                                                                                                                                                            iMac-Jakub.local: Sun Apr 11 09:45:36 2021

NAME                    READY   MESSAGE                         LAST SCAN                       SUSPENDED
imagerepository/podinfo True    successful scan, found 34 tags  2021-04-11T09:44:46+02:00       False

NAME                    READY   MESSAGE                                                                                                 LATEST IMAGE
imagepolicy/podinfo     True    Latest image tag for '247635813899.dkr.ecr.eu-central-1.amazonaws.com/hey-flux' resolved to: sdd9      247635813899.dkr.ecr.eu-central-1.amazonaws.com/hey-flux:sdd9

NAME                                    READY   MESSAGE                                                         LAST RUN                        SUSPENDED
imageupdateautomation/flux-system       True    no updates made; last commit 58dd783 at 2021-04-11T07:35:46Z    2021-04-11T09:44:53+02:00       False


``` 





structure (my-private-repo)
-file1.yml
-file2.yml
-file3.yml
---eks(directory)
-------heyflux(directory)
----------values.yaml
----------Chart.yaml
----------rest chart files

file1.yml
```
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  checkout:
    branch: master
    gitRepositoryRef:
      name: podinfo
  commit:
    authorEmail: fluxcdbot@users.noreply.github.com
    authorName: fluxcdbot
    messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
  interval: 1m0s
  push:
    branch: master
  update:
    path: ./eks/heyflux
    strategy: Setters
```
file2.yml
```
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  image: 247635813899.dkr.ecr.eu-central-1.amazonaws.com/hey-flux
  interval: 1m0s
  secretRef:
    name: aws-ecr
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: podinfo
  filterTags:
    pattern: '^sdd[a-fA-F0-9]+'
  policy:
    alphabetical:
      order: asc
```

file3.yml:
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@bitbucket.org/muumerepos/my-private-repo.git
  secretRef:
    name: ssh-credentials
  ref:
    branch: master
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: heyflux
  namespace: flux-system
spec:
  interval: 1m
  upgrade:
    remediation:
      retries: -1
  chart:
    spec:
      chart: ./eks/heyflux
      valuesFile: ./eks/heyflux/values.yaml
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: flux-system
      interval: 1m
```

eks/heyflux/values.yaml
```
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
envName: "default"
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
muumeerp:
  image:
    repository: 247635813899.dkr.ecr.eu-central-1.amazonaws.com/hey-flux
    tag: sdd9 # {"$imagepolicy": "flux-system:podinfo:tag"}
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
```

**Comment by dmitry-rachkov** [comment]
Hey there guys! Enjoyed so far my fluxcd experience, though similarly to **kadzielawa** I have issues with automatic image updates to git repo.

Here is some info around it:

### Repo structure 
```
 ── cd
│   ├── flux-system
│   │   ├── gotk-components.yaml
│   │   ├── gotk-sync.yaml
│   │   └── kustomization.yaml
│   └── sync
│       ├── flagger
│       │   ├── blueGreen.yaml
│       │   └── load-tester
│       └── flux
│           ├── helm_release.yaml
│           └── helm_source.yaml
├── flagger
└── rest-api-app
    ├── Chart.yaml
    ├── charts
    ├── templates
    └── values.yaml
```
### bootstrap was done like this
```
         flux bootstrap gitlab \
         --owner=dmitry_rachkov/cd \
         --repository=BlueGreen \
         --branch=master \
         --path=cd \
         --components-extra=image-reflector-controller,image-automation-controller \
         --token-auth
```
### image creation
```
         flux create image repository rest-api-app \
         --image=registry.hub.docker.com/dmitryrachkov/rest-api \
         --interval=1m
```
### image policy
```
          flux create image policy rest-api-app \
         --image-ref=rest-api-app \
         --select-semver=">=0.0.6"
```
### image update automation
```
         flux create image update rest-api-app \
          --git-repo-ref=rest-api-app \
          --git-repo-path="./rest-api-app" \
          --checkout-branch=master \
          --push-branch=master \
          --author-name=dmitry_rachkov \
          --author-email=email@email.com \
          --commit-template="{{range .Updated.Images}}{{println .}}{{end}}" 
```

The update is expected to happen over helm release (based on GitRepository - helm source object)

**helm_source.yaml**
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: rest-api-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://gitlab.com/dmitry_rachkov/cd/BlueGreen.git
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/rest-api-app/
    !/cd/sync/flux

```
**helm_release.yaml**

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rest-api-app
  namespace: rest-api-app
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ./rest-api-app
      sourceRef:
        kind: GitRepository
        name: rest-api-app
        namespace: flux-system
      valuesFiles:
        - ./rest-api-app/values.yaml
  values:
    deployment:
      image:
        tag: 0.0.16 # {"$imagepolicy": "rest-api-app:rest-api-app:tag"}
```

Unfortunately automatic commit just doesn't happen with this setup for me though as I've read above and in documentation it should, would be grateful for ideas or hints.
Cheers
