### ISSUE TITLE
Feature request: configurable branch force pushing

### ISSUE THREAD

**Issue by jracollins** [fluxcd/image-automation-controller#205]
## Use case: 

A workflow I am using currently is to push the image automation updates to a different branch than the one flux is watching. A Github action then opens a PR on any commit to that branch (and the branch is subsequently pruned upon merging). 

This allows users to approve/deploy releases manually, whilst keeping most of the workflow (i.e: committing and pushing tags) automated. 

## Current Issue:

If a branch with image updates is created by flux, and a new commit comes into the main branch that it was branched off, any subsequent updates are blocked because the Git history on the opened branch is out of sync. The "solution" is to rebase the branch and add the image update commit. However this requires a force push to the new branch, which flux currently does not do. 

This will occur when using separate branches for multiple applications image automation updates. 

Eg:
```
/main
/app-a-update 
/app-b-update
```

If using flux to commit on the same branch as it is watching (ie, auto deploy on new image tag) this is a non issue, as there is no rebasing required. 

However if in this example, /app-a-update branch is merged, the commit on /app-b-update needs to be rebased (and then forced pushed), currently this is not possible and fails. The current workaround I am using is to manually delete the branch and wait for flux to recreate.  

## Proposal:

```YAML
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: my-application
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: my-application
  update:
    path: ./production
    strategy: Setters
  git:
    checkout:
      ref:
        branch: main
    push:
      branch: my-application-production-update
      force: true # this would be the proposed setting/flag
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
```

This should default to false and remain backward compatible.

Branch protection in GitHub etc can also prevent any unintended rewriting of important branches. 

Initial Discussion in Flux Slack: https://cloud-native.slack.com/archives/CLAJ40HV3/p1627660144049300
