### ISSUE TITLE
Getting 'auth error: EOF' when referencing a GitRepository pulling via SSH

### ISSUE THREAD

**Issue by wolfmah** [fluxcd/image-automation-controller#210]
When creating an `ImageUpdateAutomation` that reference a `GitRepository` in HTTPS mode, `ImageUpdateAutomation` is able to reconcile. When referencing a `GitRepository` in SSH mode, it gives this error: `auth error: EOF`.

`GitRepository` in HTTPS mode:
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: my-app-https
  namespace: flux-system
spec:
  gitImplementation: go-git
  ignore: |
    # exclude all
    /*
    # include kustomize dir
    !/kustomize
    # exclude file extensions from kustomize dir
    /kustomize/**/*.md
    /kustomize/**/*.txt
  interval: 15m0s
  ref:
    branch: develop
  secretRef:
    name: bitbucket-https-credentials
  timeout: 20s
  url: https://bitbucket.org/my-group/my-app
```

`GitRepository` in SSH mode:
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: my-app-ssh
  namespace: flux-system
spec:
  gitImplementation: go-git
  ignore: |
    # exclude all
    /*
    # include kustomize dir
    !/kustomize
    # exclude file extensions from kustomize dir
    /kustomize/**/*.md
    /kustomize/**/*.txt
  interval: 15m0s
  ref:
    branch: develop
  secretRef:
    name: bitbucket-ssh-credentials
  timeout: 20s
  url: ssh://git@bitbucket.org/my-group/my-app
```

`ImageUpdateAutomation` (only `spec.sourceRef.name` changes while testing the two `GitRepository`):
```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: my-app
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: develop
    commit:
      author:
        email: flux@my-domain.com
        name: flux
      messageTemplate: |
        [ci skip] -
        {{range .Updated.Images}}{{println .}}{{end}}
    push:
      branch: develop
  interval: 15m0s
  sourceRef:
    apiVersion: source.toolkit.fluxcd.io/v1beta1
    kind: GitRepository
    name: my-app-https
  update:
    path: ./kustomize/dev
    strategy: Setters
```

The status result when `spec.sourceRef.name == my-app-ssh`:
```yaml
status:
  conditions:
  - lastTransitionTime: "2021-08-05T11:13:23Z"
    message: 'auth error: EOF'
    reason: ReconciliationFailed
    status: "False"
    type: Ready
  lastAutomationRunTime: "2021-08-05T11:09:05Z"
  lastHandledReconcileAt: "2021-08-05T07:15:48.299246-04:00"
  observedGeneration: 3
```

The status result when `spec.sourceRef.name == my-app-https`:
```yaml
status:
  conditions:
  - lastTransitionTime: "2021-08-05T11:16:58Z"
    message: no updates made
    reason: ReconciliationSucceeded
    status: "True"
    type: Ready
  lastAutomationRunTime: "2021-08-05T11:17:28Z"
  lastHandledReconcileAt: "2021-08-05T07:16:57.526803-04:00"
  observedGeneration: 4
```
