### ISSUE TITLE
HelmRelease file not updated 

### ISSUE THREAD

**Issue by derrickburns** [fluxcd/image-automation-controller#214]
@stefanprodan As you know, I have been using your tools for a long time. My general experience is that the tools are rock solid.

Today a colleague reported that an image was not being updated. I inspected our cluster.  The Image Automation controller had been running for 4 days.  It had made updates as recently as last night.  There were no error messages in the logs.  In other words, from the perspective of the Image Automation controller, everything was running fine.

I looked for an ImagePolicy for the image in question. I found one.  The policy *had* been updated to the new image hours earlier. The annotation to instruct the Image Automation controller was attached to a HelmRelease.  That file **had not** been modified with the new image tag.  However, that file **had** been updated by the image automation controller in the last 4 days.  

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mock-metadata-service
spec:
  interval: 5m
  chart:
    spec:
      chart: .
      version: "0.0.4"
      sourceRef:
        kind: GitRepository
        name: mock-metadata-service
        namespace: shared
      interval: 1m
  values:
    name: mock-metadata-service
    imagePullSecrets:
      - name: ecr-credentials-sync
    images:
      tag: 21.0811.1547.38-70e9909c-master # {"$imagepolicy": "shared:mock-metadata-service:tag"}
```

I restarted the Image Automation controller and it quickly updated the Gitlab repo to reflect the proper version of the Image tag.

So, I am left to conclude that either an error occurred that was not properly logged or there is another bug.
