### ISSUE TITLE
ImageUpdateAutomation not working bacause of git clone error

### ISSUE THREAD

**Issue by AshuDubey91** [fluxcd/image-automation-controller#228]
I am using github enterprise as gitRepositorySource in ImageUpdateAutomation. 
image-automation-controller image : `ghcr.io/fluxcd/image-automation-controller:v0.14.0`
git source configuration:
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: k8source-demo
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: https://GHE-url
```
imageupdateAutomation configuration : 
```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: k8-auto-update
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    apiVersion: source.toolkit.fluxcd.io/v1beta1
    kind: GitRepository
    name: k8source-demo
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdbot@github.com
        name: fluxcdbot
      messageTemplate: 'updated image'
    push:
      branch: feature/auto-update
  update:
    path: ./cluster
    strategy: Setters
```

I am getting following error while enabling it.

```
$ flux get image update k8-auto-update
NAME         READY   MESSAGE                                                                                                                                         LAST RUN        SUSPENDED
k8-auto-update False   unable to clone 'GHE url', error: server requires authentication that we do not support                     False
```
I have used ghe-auth-token as secret in source. This source configuration perfectly works for kustomizations for deployments on k8 clusters whereas when I am using it in imageupdateAutomation it is failing with above error.

Could you please suggest any solution to this? or may be point out what is wrong here?
