### ISSUE TITLE
Image name gets cut off in kustomization

### ISSUE THREAD

**Issue by kharf** [fluxcd/image-automation-controller#261]
After updating to flux 0.22, our image automation does not work correctly anymore, since the image names get cut off in the kustomization. Even after fixing it, flux always renames it.

kustomization:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: v3
resources:
  - ../../bases/invoice-service
  - sealed-secret.yaml
  - config-map.yaml
  - canary.yaml
images:
  - name: invoice-service
    newName: eu.gcr.io/xxxxxxxxxxxxxxxxxxx/xxxxxx-invoice-service # {"$imagepolicy": "flux-system:invoice-service:name"}
    newTag: 2021-11-11-1015-bd0a681-dev # {"$imagepolicy": "flux-system:invoice-service:tag"}
```
In the example above flux removes the "e" from "service" and sets the newName in the kustomization like this:
`newName: eu.gcr.io/xxxxxxxxxxxxxxxxxxx/xxxxxx-invoice-servic # {"$imagepolicy": "flux-system:invoice-service:name"}`

We didn't change anything before upgrading from flux 0.21 to 0.22.

ImageRepository:
```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: invoice-service
  namespace: flux-system
spec:
  image: eu.gcr.io/xxxxxxxxxxxxxxxxxxx/xxxxxx-invoice-service
  interval: 1m0s
  secretRef:
    name: gcr-credentials
 ```
ImagePolicy:
```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: invoice-service
  namespace: flux-system
spec:
  filterTags:
    pattern: '^(?P<ts>.*)-[a-fA-F0-9]{7}-dev'
    extract: '$ts'
  imageRepositoryRef:
    name: invoice-service
  policy:
    alphabetical:
      order: asc
```
ImageUpdateAutomation:
```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: flux@xxx.com
        name: Flux Bot 🤖
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  update:
    path: ./apps/dev
    strategy: Setters
```

If you need more information, I can help!
