### ISSUE TITLE
unable to clone: Certificate

### ISSUE THREAD

**Issue by charlie-haley** [fluxcd/image-automation-controller#298]
I've recently configured image update automations on one of our clusters, all the image repositories and image policies seem to reconcile fine.
 
However the images never updated and I get this event from the `ImageUpdateAutomation` - `unable to clone: Certificate`

```
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: myfluxbot@users.noreply.github.com
        name: myfluxbot
    push:
      branch: master
  update:
    path: ./manifests
    strategy: Setters
```
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: ssh://github.com/my/repo
  secretRef:
    name: infra-git-secret

```
It's referencing the same `GitRepository` we use in our Flux Kustomizations (which work perfectly)

Here's the Git

**Flux version: 0.25.2
Image controller: 0.19.0**

**Comment by hiddeco** [comment]
What is the format of the private key you are making use of?

**Comment by charlie-haley** [comment]
> What is the format of the private key you are making use of?

It's a public and private key, also with a known_hosts

```
apiVersion: v1
kind: Secret
metadata:
  name: infra-git-secret
  namespace: flux-system
data:
  identity: <redacted>
  identity.pub: <redacted>
  known_hosts: <redacted>
  ```
