### ISSUE TITLE
inline image policy marker comments merge problem

### ISSUE THREAD

**Issue by bob-rohan** [fluxcd/image-automation-controller#312]
Supposing `podinfo` supported release branches (which I recommend against, but lots of places do use), then you might have a test environment setup with image automation defining inline image policy marker comments such as follows   

`newTag: release-dcd9b99-1643898245 # {"$imagepolicy": "flux-system:podinfo-release:tag"}`

To deploy to production, these image IDs would be merged from the release branch, to the main.

In addition to supporting release branch based deployments, `podinfo` maintainers would also like Flux to support pain free hotfixes, with a view to using this for continuous delivery on other services. Then you might have an production environment  setup with image automation defining inline image policy marker comments such as follows.

`newTag: main-dcd9b99-1643898245 # {"$imagepolicy": "flux-system:podinfo-main:tag"}`

However by merging the `release` branch to `main`, the inline image policy marker comment is erroneously updated to from `podinfo-main` to `podinfo-release`. The goal is to have 

`newTag: release-dcd9b99-1643898245 # {"$imagepolicy": "flux-system:podinfo-main:tag"}`

See the tag is now set to `release-dcd9b99-1643898245`, but the image policy will continue to identify hotfixes from `podinfo-main`.

It would be better not to use inline comments

**Comment by stefanprodan** [comment]
You can place these markers on the Flux Kustomization object that applies the app on an environment. The one in `clusters/staging` will use different policy than the one in `clusters/production` e.g.:

`clusters/staging/podinfo.yaml`:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  images:
    - name: ghcr.io/stefanprodan/podinfo
      newName: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "flux-system:podinfo-main:name"}
      newTag: 5.0.0 # {"$imagepolicy": "flux-system:podinfo-main:tag"}
```

`clusters/production/podinfo.yaml`:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  images:
    - name: ghcr.io/stefanprodan/podinfo
      newName: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "flux-system:podinfo-release:name"}
      newTag: 5.0.0 # {"$imagepolicy": "flux-system:podinfo-release:tag"}
```
