### ISSUE TITLE
Timeout enforcement

### ISSUE THREAD

**Issue by pjbgf** [fluxcd/image-automation-controller#371]
Image Automation Controller does not have a `Spec.Timeout`, as most other controllers do, instead it applies the `Spec.Timeout` set in the referred source, and uses that timeout for each Git related operation.

However, in some cases the reconcilation seems to get stuck for long periods of time (based on the `gotk_reconcile_duration_seconds_sum` metric):
![image](https://user-images.githubusercontent.com/5452977/170861253-03440643-e1d2-41c5-979c-620bf86b0087.png)

ImageUpdateAutomation YAML:
```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: github-branch
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: push-branch
  interval: 60s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: ./clusters/production
    strategy: Setters
```
