### ISSUE TITLE
Flux not updating images in multiple namespace

### ISSUE THREAD

**Issue by thulasidassrinivasan** [fluxcd/image-automation-controller#387]
Hi Team,

I have created ImageRepository, ImagePolicy, ImageUpdateAutomation in flux-system namespace. 

I have same application running in two different namespace and both are having the same policy marker.

Application A - namespace A
Application A - namespace B

Flux only updates the application running in namespace A but ignores it in namespace B. I am not able to understand the reason. How to troubleshoot this and make it work ?

**Comment by stefanprodan** [comment]
> Flux only updates the application running in namespace A but ignores it in namespace B.

I guess the manifests for namespace B are not found in the update path:

```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
 .....
  update:
    path: ./clusters/my-cluster
    strategy: Setters
```
