### ISSUE TITLE
Reconciler error: early EOF

### ISSUE THREAD

**Issue by Sonlis** [fluxcd/image-automation-controller#405]
I did setup an image repository, image policy and image update automation. The image repository and image policy work correctly, and find the latest image based on the policy. 
However, the image-automation-controller returns this error: 
```
{"level":"error","ts":"2022-07-07T13:16:53.005Z","logger":"controller.imageupdateautomation","msg":"Reconciler error","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"license-service","namespace":"sharpershape","error":"early EOF"}
```
The ImageUpdateAutomation sourceRef is as follows: 
```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: license-service
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-dev-source-repository
    namespace: admin
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-dev-source-repository
  namespace: admin
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: ssh://git@github.com/companyName/flux-dev-v2
``` 

This gitRepository source is also used by the source-controller and can fetch properly the repository. I have also checked that the ssh-key used by this gitRepository has both read and write rights, which it does (we however use ssh-keys for the user flux, not one per repository. It has then access to multiple repository with only one ssh key).
The error is a bit obscure, and the only similar I could find in the github issues was solved by having write permissions on the ssh key, which is already setup.

image-automation-controller version: v0.23.4
