### ISSUE TITLE
ImagePolicy with mixed policy types

### ISSUE THREAD

**Issue by roman-chub** [fluxcd/image-automation-controller#418]
I have an issue with updating image due to the mixed naming of tag which contained both numbers and letters (I'm using `CI_COMMIT_SHORT_SHA` once pushing new image to repo in my gitlab pipeline). It's looking like following:
```
sandbox-1214bc9i
sandbox-cd14bcbc
```

Once I tried to use `numerical` policy:
```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: image-policy-sandbox
spec:
  imageRepositoryRef:
    name: image-repo
  filterTags:
    pattern: '^sandbox-[0-9a-z]+'
  policy:
    numerical:
      order: asc
```
I got following error:
```
imagepolicy/image-policy-sandbox      	            	False	Cannot determine latest tag for policy: failed to parse invalid numeric value 'sandbox-ce597c69' 
```
If I'm using `alphabetical` policy:
```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: image-policy-sandbox
spec:
  imageRepositoryRef:
    name: image-repo
  filterTags:
    pattern: '^sandbox-[0-9a-z]+'
  policy:
    alphabetical:
      order: asc
```
Image update is working but didn't use the latest image for automation and pickup much older image tag

Sorry, it may be described somewhere but I tried almost all patterns and it didn't work correctly. Could you please provide me some info how to make it workable and to teach my automation pickup latest image from `sandbox-*`?

**Comment by pjbgf** [comment]
@roman-chub please take a look at our "sortable image tags" guide: https://fluxcd.io/docs/guides/sortable-image-tags/.

**Comment by roman-chub** [comment]
@pjbgf thanks for the feedback but I already checked that and don't know what should be changed in pattern. I have no any timestamps or another staff which may be extracted and my `CI_COMMIT_SHORT_SHA` should covered by this `[0-9a-z]+`. Am I not right?

**Comment by roman-chub** [comment]
@pjbgf I've tried to make my tag as `$CI_COMMIT_BRANCH-$CI_PIPELINE_IID` to receive something like `sandbox-59` but policy is not even trying to find numerical tag after `sandbox-*`

```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: mailchimp-image-policy-sandbox
spec:
  imageRepositoryRef:
    name: mailchimp-image-repo
  filterTags:
    pattern: '^sandbox-(?P<sha>.*)'
    extract: '$sha'
  policy:
    numerical:
      order: asc
```
and send error messages like below:

```
  Warning  error   3m29s (x57747 over 3d15h)  image-reflector-controller  (combined from similar events): Cannot determine latest tag for policy: failed to parse invalid numeric value 'c8dbabd6' 
```
Could you please specify what should be done here to make it workable?
