### ISSUE TITLE
image-automation-controller not working after upgrade

### ISSUE THREAD

**Issue by uderik** [fluxcd/image-automation-controller#419]
image-automation-controller v0.24.1 crash loop after update to latest version
log attached

[image-automation-controller.log](https://github.com/fluxcd/image-automation-controller/files/9311074/image-automation-controller.log)

**Comment by pjbgf** [comment]
@uderik do you mind confirming what version were you running before the update?

Is this happening intermittently or at every reconciliation?

**Comment by uderik** [comment]
@pjbgf 0.23.5 works fine
0.24.1/0.24.0 versions does not work, crashing after start

**Comment by darkowlzz** [comment]
Hi, can you provide some more information about your setup? The git provider, self-hosted or managed and parts of  ImageUpdateAutomation and GitRepository spec that can be shared. I've been trying to reproduce it but seems to work fine for me.

**Comment by darkowlzz** [comment]
Also, can you please enable debug logs by setting `--log-level=debug` in the container arguments.

You can use this patch in your flux kustomization if flux your image-automation-controller is managed by flux itself:
```yaml
patches:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: image-automation-controller
      namespace: flux-system
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --log-level=debug
```
please adjust any names according to your setup.
