### ISSUE TITLE
cannot fetch remote branch: EOF

### ISSUE THREAD

**Issue by PierreBart** [fluxcd/image-automation-controller#422]
## Describe the bug

After upgrading Flux from v2.29.5 to v0.32.0, the Image Automation controller throws the following error:
```bash
{"error":"cannot fetch remote branch: EOF", "level":"error", "logger":"controller.imageupdateautomation", "msg":"Reconciler error", "name":"staging-image-update", "namespace":"flux2", "reconciler group":"image.toolkit.fluxcd.io", "reconciler kind":"ImageUpdateAutomation", "ts":"2022-08-24T12:42:28.576Z"}
```

This ImageUpdateAutomation object is deployed on the cluster:
```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: staging-image-update
  namespace: flux2
spec:
  git:
    checkout:
      ref:
        branch: master
    commit:
 [...]
    push:
      branch: master
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux2
  update:
    path: ./apps/staging
    strategy: Setters
```

I am facing the same issue in v0.31.5 but not in v0.30.2.

## Expected behavior

The Image Automation controller throws no error.

## Kubernetes version

GKE 1.23.8

## Git provider

Gitlab private repository.

## Additional context

In Slack, @pjbgf noticed I use the same branch for pushing and pulling the sources in the `ImageUpdateAutomation` definition. He recommended I remove the `push.branch` field from the spec and that did fix the error.
