### ISSUE TITLE
ImageUpdateAutomation not respecting the interval specified

### ISSUE THREAD

**Issue by poojaac** [fluxcd/image-automation-controller#433]
We have configured ImageUpdateAutomation and have given the interval of 24h to make the flux update the images once in a day. But ImageUpdateAutomation is not respecting the interval specified and updating the Git repo when the image-policy is picking the latest image.

Also, if a git path is specified to updated the image versions and markers are added in the file, the ImageUpdateAutomation is not making a single commit with changes to all images in that file when image-policy is picking the latest version for multiple services. Instead its making multiple commits to the same file one after the other

```
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: infra
  namespace: pftp-da-team
spec:
  sourceRef:
    kind: GitRepository
    name: pftp-da-team
  interval: 24h
  update:
    strategy: Setters
    path: ./infra/patch-helmreleases.yaml
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        name: cit noreply (ETAS-DEV/ENG-TP)
        email: noreply.cit@etas.com
      messageTemplate: 'Auto deployment of docker images to infra by flux'
    push:
      branch: master
  # suspend: true
```

![image](https://user-images.githubusercontent.com/52164525/189307272-41aa1f39-a022-431f-b166-61dd3a29c958.png)
