### ISSUE TITLE
Uninstall does not delete Image automation CRD

### ISSUE THREAD

**Issue by danielkimuipath** [fluxcd/image-automation-controller#435]
Hi, I'm using Image automation CRDs in my cluster. My cluster is has a set up to fetch images from Azure ACR and there was an issue with fetching the images. So I tried to uninstall the flux and reinstallling the flux, but `flux uninstall` command does not clean up the image automation ACRs.

```
flux uninstall
Are you sure you want to delete Flux and its custom resource definitions: y
► deleting components in flux-system namespace
► deleting toolkit.fluxcd.io finalizers in all namespaces
► deleting toolkit.fluxcd.io custom resource definitions
✔ CustomResourceDefinition/imagepolicies.image.toolkit.fluxcd.io deleted
✔ CustomResourceDefinition/imagerepositories.image.toolkit.fluxcd.io deleted
✔ Namespace/flux-system deleted
✔ uninstall finished
```
after the delete
```
k get crd -A
...
imagepolicies.image.toolkit.fluxcd.io            2022-09-08T22:32:15Z
imagerepositories.image.toolkit.fluxcd.io        2022-09-08T22:32:15Z
```

Even I tried to force delete, it still does not work:
```
 k delete crd imagepolicies.image.toolkit.fluxcd.io --force --grace-period=0
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
customresourcedefinition.apiextensions.k8s.io "imagepolicies.image.toolkit.fluxcd.io" force deleted
```
Can someone help me how to clean up the CRD properly?

**Comment by danielkimuipath** [comment]
This seems to be the finalizer setting in the CRD - once the finalizers are removed manually, CRD were cleaned up. However, I believe this needs to be sorted by `flux uninstall` command

**Comment by stefanprodan** [comment]
Are you using the latest version of Flux? If not get the latest and see if it fixes the issue for you.

**Comment by danielkimuipath** [comment]
Here is the flux version of the issue:
```
flux --version
flux version 0.30.2
```

```
flux version
flux: v0.30.2
helm-controller: v0.22.2
image-automation-controller: v0.24.1
image-reflector-controller: v0.20.0
kustomize-controller: v0.27.0
notification-controller: v0.25.1
source-controller: v0.26.1
```

I will update it with newest version of flux shortly

**Comment by danielkimuipath** [comment]
```
k get crd
NAME                                             CREATED AT
alertproviders.flagger.app                       2022-08-31T20:41:08Z
alerts.notification.toolkit.fluxcd.io            2022-09-12T22:47:02Z
authorizationpolicies.security.istio.io          2022-08-31T20:40:38Z
buckets.source.toolkit.fluxcd.io                 2022-09-12T22:47:03Z
canaries.flagger.app                             2022-08-31T20:41:08Z
certificaterequests.cert-manager.io              2022-08-31T20:40:01Z
certificates.cert-manager.io                     2022-08-31T20:40:01Z
challenges.acme.cert-manager.io                  2022-08-31T20:40:02Z
clusterissuers.cert-manager.io                   2022-08-31T20:40:02Z
destinationrules.networking.istio.io             2022-08-31T20:40:38Z
envoyfilters.networking.istio.io                 2022-08-31T20:40:38Z
gateways.networking.istio.io                     2022-08-31T20:40:38Z
gitrepositories.source.toolkit.fluxcd.io         2022-09-12T22:47:01Z
helmcharts.source.toolkit.fluxcd.io              2022-09-12T22:47:01Z
helmreleases.helm.toolkit.fluxcd.io              2022-09-12T22:47:02Z
helmrepositories.source.toolkit.fluxcd.io        2022-09-12T22:47:01Z
imagepolicies.image.toolkit.fluxcd.io            2022-09-12T22:47:02Z
imagerepositories.image.toolkit.fluxcd.io        2022-09-12T22:47:01Z
imageupdateautomations.image.toolkit.fluxcd.io   2022-09-12T22:47:03Z
issuers.cert-manager.io                          2022-08-31T20:40:02Z
istiooperators.install.istio.io                  2022-08-31T20:40:38Z
kustomizations.kustomize.toolkit.fluxcd.io       2022-09-12T22:47:01Z
metrictemplates.flagger.app                      2022-08-31T20:41:08Z
ocirepositories.source.toolkit.fluxcd.io         2022-09-12T22:47:01Z
providers.notification.toolkit.fluxcd.io         2022-09-12T22:47:03Z
receivers.notification.toolkit.fluxcd.io         2022-09-12T22:47:02Z
...
...
```

After:
```
...
ocirepositories.source.toolkit.fluxcd.io         2022-09-12T22:47:01Z
...
```

This issue still exists with `ocirepositories.source.toolkit.fluxcd.io` crd

**Comment by danielkimuipath** [comment]
```
k edit crd ocirepositories.source.toolkit.fluxcd.io
```

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.7.0
  creationTimestamp: "2022-09-12T22:47:01Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2022-09-13T19:56:51Z"
  finalizers:
  - customresourcecleanup.apiextensions.k8s.io
  generation: 1
```

I see finalizer is still there after the deletion, which I had to update manually.

This issue went aware with other crd like 
```
imagepolicies.image.toolkit.fluxcd.io            2022-09-12T22:47:02Z
imagerepositories.image.toolkit.fluxcd.io        2022-09-12T22:47:01Z
imageupdateautomations.image.toolkit.fluxcd.io   2022-09-12T22:47:03Z

```
