### ISSUE TITLE
Feature request: Add git push option for arbitrary refspec

### ISSUE THREAD

**Issue by aristapimenta** [fluxcd/image-automation-controller#509]
Hi, in my company we use Gerrit, and there's a special reference which opens the equivalent of merge/pull requests when commits are pushed to this reference:

```shell
git push origin HEAD:refs/for/master
```

It would be really great if we could specify such arbitrary reference, maybe like this:

```yaml
spec:
  git:
    push:
      refspec: HEAD:refs/for/master
```

**Comment by makkes** [comment]
https://github.com/fluxcd/source-controller/issues/1017 might help when implementing this.

The `ref` would be `refs/for/master`.

**Comment by brovoca** [comment]
We heavily use Gerrit in our team and suffer from not being able to create Gerrit changes, as described by @aristapimenta. When I try to configure `refs/heads/refs/for/master` or `refs/for/master`, an actual branch is created, which isn't what should happen.

**Comment by stefanprodan** [comment]
I think adding refs would also allow Flux to work with GitLab, but we may need a lis of refs instead of just one item. cc @hiddeco

**Comment by hiddeco** [comment]
GitLab integrations I was thinking about is different, and called "push options". See:

- https://docs.gitlab.com/ee/user/project/push_options.html
- https://github.com/fluxcd/flux2/discussions/3490

**Comment by stefanprodan** [comment]
@hiddeco then we can add ref name to IAC CRD same as we did with GitRepo and for push options we can have a separate field right?

**Comment by aryan9600** [comment]
yes we can modify the CRD where the ref name would be specified under `spec.git.push.refName`.

**Comment by autotmp** [comment]
> GitLab integrations I was thinking about is different, and called "push options". See:
> 
>     * https://docs.gitlab.com/ee/user/project/push_options.html
> 
>     * [Allow specifying git push options for image automation controller flux2#3490](https://github.com/fluxcd/flux2/discussions/3490)

Found this thread looking for a way to create Merge Requests via GitLab's push options. Very exciting!

**Comment by cyclimse** [comment]
Looking forward to this feature as well for Gitlab! It looks like gogit supports `push_options` https://github.com/go-git/go-git/pull/399

**Comment by hiddeco** [comment]
> @hiddeco then we can add ref name to IAC CRD same as we did with GitRepo and for push options we can have a separate field right?

Yes. If we vote for `.spec.git.push.ref`, I think the counterpart for push options would be `.spec.git.push.options`. This would take a string list of options.

**Comment by aryan9600** [comment]
as i pointed out in today's community meeting, the most apt name is `.spec.git.push.refspec` as a Git Refspec and a Git ref are two different things. (ref: https://git-scm.com/book/en/v2/Git-Internals-The-Refspec, https://git-scm.com/book/en/v2/Git-Internals-Git-References)

**Comment by brovoca** [comment]
Eagerly waiting for this...

**Comment by aryan9600** [comment]
Even if we get this feature in, I don't think image-automation-controller will be compatible with Gerrit. Gerrit uses the `commit-msg` Git hook to insert a identifier called [`Change-Ids`](https://gerrit-review.googlesource.com/Documentation/user-changeid.html). Atm [go-git](https://github.com/go-git/go-git), the Git library we use does not support Git hooks. Even if it did, the `commit-msg` Git hook that Gerrit requires is written in bash and shells out to default Git installation in the machine (ref: https://gerrit-review.googlesource.com/Documentation/cmd-hook-commit-msg.html).

That is a big no-no in Flux, and one of the core reasons we use a library and don't shell out ourselves to push, pull, etc.
We can still get this feature in as it might be helpful for other scenarios, but I don't think it solve the Gerrit use case. Please note that my knowledge about Gerrit is extremely limited, so feel free to correct me I am wrong.

**Comment by brovoca** [comment]
@aryan9600 I've written my own messageTemplate that generates a Change-Id:

```yaml
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system-master
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: master
    push:
      branch: master
    commit:
      author:
        email: flux@localdomain
        name: flux
      messageTemplate: |
        Perform automatic image update

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Updated.Files -}}
        - {{ $filename }}
        {{ end }}
        Objects:
        {{ range $resource, $_ := .Updated.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
        {{ end }}
        Images:
        {{ range .Updated.Images -}}
        - {{ . }}
        {{ end }}
        {{- $ChangeId := .AutomationObject -}}
        {{- $ChangeId = printf "%s%s" $ChangeId ( .Updated.Files | toString ) -}}
        {{- $ChangeId = printf "%s%s" $ChangeId ( .Updated.Objects | toString ) -}}
        {{- $ChangeId = printf "%s%s" $ChangeId ( .Updated.Images | toString ) }}
        Change-Id: {{ printf "I%s" ( sha256sum $ChangeId | trunc 40 ) }}
```
