### ISSUE TITLE
Image Automation Controller is reformatting inline blocks in a single line

### ISSUE THREAD

**Issue by ruiengana** [fluxcd/image-automation-controller#528]
When a manifest has block configuration like below and is updated by image automation controller, blocks are overwritten as a single line of code making it unreadable. Code blocks should not be reformatted.

For example, this is pipe block
```
  config: |
    _format_version: "2.1"
    _transform: true
    services:
    - name: example
      url: https://example.org
      routes:
      - name: example
        paths:
        - /example
```

After image automation controller commit becomes

```
  config: "_format_version: \"2.1\"\n    _transform: true\n    services:\n    - name: example\n      url: https://example.org\n      routes:\n      - name: example\n        paths:\n        - /example\n"
```

This behaviour is unexpected, we would like blocks to stay exactly as they were before.

**Comment by stefanprodan** [comment]
> This behaviour is unexpected, we would like blocks to stay exactly as they were before.

We use kustomize kyaml to mutate the YAMLs and this is how it behaves. I suggest you move the `images` block that's being patched, to a Flux Kustomization e.g.

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  images:
    - name: ghcr.io/stefanprodan/podinfo
      newName: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "flux-system:podinfo:name"}
      newTag: 5.0.0 # {"$imagepolicy": "flux-system:podinfo:tag"}
```
