### ISSUE TITLE
Yaml written by ImageUpdateAutomation cannot be reconciled when using variables

### ISSUE THREAD

**Issue by GevatterGaul** [fluxcd/image-automation-controller#566]
I have a deployment with an image that I want to be updated automatically. Everything works when I use a flat yaml file (no variables, everything explicit). The new images get recognized and the file is overwritten to reflect the new tag.
But when I start using variables in the file after one image update the file can no longer be reconciled because the format seems to be wrong.

Note: 
.Values.name = qa

Deployment file:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    namespace: {{ .Values.name }}
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: registry.local/gui/gui:0.0.1-1690901017 # {"$imagepolicy": "qa:frontend-policy"}
        imagePullPolicy: Always
```

Deployment file after update:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    namespace: {? {.Values.name: ''} : ''}
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: registry.local/gui/gui:0.0.1-1690902238 # {"$imagepolicy": "qa:frontend-policy"}
        imagePullPolicy: Always
```

Policy:
```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name:  frontend-policy
  namespace: {{ .Values.name }}
spec:
  imageRepositoryRef:
    name: frontend-repo
    namespace: {{ .Values.name }}
  filterTags:
    pattern: '^[0-9\.]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
```

Repo:
```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: frontend-repo
  namespace: {{ .Values.name }}
spec:
  image: registry.local/gui/gui
  interval: 5m
  secretRef:
    name: proxyregsecret
```

Flux the errors with "converting yaml to json values".

Any ideas? I still want to use variables in my yaml files.

**Comment by makkes** [comment]
Flux doesn't handle templates in manifests like `namespace: {{ .Values.name }}`. This looks like Helm templates so what you would need to do is wrap these manifests in a Helm chart.

**Comment by GevatterGaul** [comment]
So we worked around it by putting the image and version number in a value.yml of the Helm chart and referencing the Helm chart. Structure as in the [docs](https://fluxcd.io/flux/guides/repository-structure/):

```
├── src
└── chart
    ├── templates
    ├── values.yaml 
    └── values-prod.yaml
```

Is that an acceptable way to do it? If yes, I would close this ticket.

**Comment by stefanprodan** [comment]
The marker should go on the HelmRelease, example here https://fluxcd.io/flux/guides/image-update/#configure-image-update-for-custom-resources

**Comment by GevatterGaul** [comment]
We referenced the value file like this:

```yaml 
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  ...
spec:
  chart:
    spec:
      chart: somechart
      sourceRef:
        kind: GitRepository
        name: flux-system
      valuesFiles:
      - someChartDir/values.yaml
      reconcileStrategy: Revision
  upgrade:
    cleanupOnFail: true
  interval: 10m0s
{{- end }}
```

Is that also ok?
