### ISSUE TITLE
"Authorization failed" and nothing else

### ISSUE THREAD

**Issue by GTorreil** [fluxcd/image-automation-controller#598]
Hello. 

First of all i'm sorry if this turns out to be a "support" issue. I reached out on Slack but could not get help.

ImageRepository and ImagePolicy works :

``` bash
➜  flux-config git:(main) flux get images policy       
NAME                            LATEST IMAGE                                READY   MESSAGE                                                                                                                                         
frontend-next-integration       registry.gitlab.com/<correct image tag>     True    Latest image tag for 'registry.gitlab.com/<image>' updated from <old tag> to <new tag>
```

ImageUpdateAutomation fails :

``` bash 
➜  flux-config git:(main) flux get images update
NAME            LAST RUN        SUSPENDED       READY   MESSAGE              
flux-system                     False           False   authorization failed
```

ImageUpdateAutomation manifest :

``` yaml
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s # TODO : 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@example.com
        name: fluxcdbot
      messageTemplate: "{{range .Updated.Images}}{{println .}}{{end}}"
    push:
      branch: main
  update:
    path: ./apps
    strategy: Setters
```

I think the message is a bit broad : is it referring to authorization for git push ? or something else ? 
I checked git repo access and protected branches, everything seems fine. 
I don't know what to look for next.
