### ISSUE TITLE
Image Automation Controller is reformatting inline blocks in a single line (Flux 2.2.0)

### ISSUE THREAD

**Issue by ruiengana** [fluxcd/image-automation-controller#616]
related to https://github.com/fluxcd/image-automation-controller/issues/528

@stefanprodan we just upgraded to Flux 2.2.0 and problem is still occurring.

All our HelmRelease files getting picked up by the Image Automation Controller are getting inline blocks reformatted to single line blocks.

When a HelmRelease manifest has a block configuration like below and is updated by image automation controller, blocks are overwritten as a single line of code making it unreadable. Code blocks should not be reformatted.

For example, this is pipe block
```
  config: |
    _format_version: "2.1"
    _transform: true
    services:
    - name: example
      url: https://example.org
      routes:
      - name: example
        paths:
        - /example
```
After image automation controller commit becomes

```
  config: "_format_version: \"2.1\"\n    _transform: true\n    services:\n    - name: example\n      url: https://example.org\n      routes:\n      - name: example\n        paths:\n        - /example\n"
```

This behaviour is unexpected, we would like blocks to stay exactly as they were before.

**Comment by stefanprodan** [comment]
Can you post here `flux check` for the cluster where you are running `image-automation-controller`.

**Comment by ruiengana** [comment]
> Can you post here `flux check` for the cluster where you are running `image-automation-controller`.

```
$ flux check
► checking prerequisites
✔ Kubernetes 1.27.7-eks-4f4795d >=1.26.0-0
► checking version in cluster
✔ distribution: flux-v2.2.0
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.37.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.37.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.31.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.2.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.2.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.2.2
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta2
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed
```

**Comment by AchazRyus** [comment]
I found a solution working for me ! In fact it's when there is a space after a `:` when non needed in your deployment file.
For example if you have  :
`annotations: 
  something:""`
If you have a space after `annotations: ` flux will commit and add \n everywhere

**Comment by ruiengana** [comment]
> config: |
>     _format_version: "2.1"
>     _transform: true
>     services:
>     - name: example
>       url: https://example.org
>       routes:
>       - name: example
>         paths:
>         - /example

Please find below a extract of the HelmRelease.
Essentially we have an umbrella chart with couple subcharts, let's say subchart A and subchart B. Subchart A has a inline block config and no image automation markers. Subchart B doesn't have inline block configs but has image automation markers.

When image automation controller picks a change on subchart B, it also changes subchart A inline block config to single line.  

```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
spec:
  releaseName: <release>
  values:
    subchart-a:
      config: |
        _format_version: "2.1"
        _transform: true
        services:
        - name: example
          url: https://example.org
          routes:
          - name: example
            paths:
            - /example
    subchart-b:
      enabled: true
      image:
        repository: <repo> # {"$imagepolicy": "flux-system:repo:name"}
        tag: <tag> # {"$imagepolicy": "flux-system:repo:tag"}
```

PS: We also have inline configs in annotations, but those are always kept OK.
