### ISSUE TITLE
I use flux for deploy my app and sync my cluster I have this error when I try image update

### ISSUE THREAD

**Issue by ale900522** [fluxcd/image-automation-controller#621]
image repository result:
`Normal   Succeeded             33m                  image-reflector-controller  successful scan: found 3 tags `                  
` Normal   Succeeded             3m10s (x6 over 28m)  image-reflector-controller  no new tags found, next scan in 5m0s `
image policy result:
` Normal   Succeeded           97s (x21 over 36m)  image-reflector-controller  Latest image tag for registry.gitlab.com/repo/image:0.00.2' resolved to 0.0.2 `
But image update the result is:
`Warning  error   64s (x11 over 13m)  image-automation-controller  authorization failed `

**Comment by ale900522** [comment]
Yes this my complete config:

image repository:

image repositories its fine
image policy its fine
image update its error authorization failed
```
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: api-repo
  namespace: flux-system
spec:
  exclusionList:
  - ^.*\.sig$
  image: registry.gitlab.com/api-repo
  interval: 5m0s
  provider: generic
  secretRef:
    name: regcred
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: access-gate-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: access-gate-registry
  policy:
    semver:
      range: '>=0.0.1'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: api-repo-gitlab  
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: admin@example.com
        name: admin
      messageTemplate: |-
        {{ range .Updated.Images -}}
        [demo] Automated image update **{{ $.AutomationObject }}** to **{{ .Identifier }}**
        {{ end -}}
        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Updated.Files -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $_ := .Updated.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
        {{ end -}}

        Images:
        {{ range .Updated.Images -}}
        - {{.}}
        {{ end -}}
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: api-repo-gitlab  #this GitRepositorie exit in flux-system namespace
    namespace: flux-system
  update:
    strategy: Setters
```
