### ISSUE TITLE
Image tag marker doesn't work in top-level yaml array

### ISSUE THREAD

**Issue by antonosmond** [fluxcd/image-automation-controller#624]
I was trying to use the image update automation to update a tag in a generic YAML file in git.
I found it doesn't update the image tag in the YAML if the YAML file has a top-level array.
A file like this doesn't work i.e. the image automation never updates the tag:
```yaml
- serviceName: busybox
  containerName: busybox
  tag: 0.0.1 # {"$imagepolicy":"flux-system:busybox:tag"}
```
But this works:
```yaml
serviceName: busybox
containerName: busybox
tag: 0.0.1 # {"$imagepolicy":"flux-system:busybox:tag"}
```
And this also works:
```yaml
tags:
  - serviceName: busybox
    containerName: busybox
    tag: 0.0.1 # {"$imagepolicy":"flux-system:busybox:tag"}
```
I'm not sure what versions of flux this applies to but I'm using:
```sh
$ flux -v
flux version 2.0.1
```
And the image automation controller tag is:
```
image: ghcr.io/fluxcd/image-automation-controller:v0.35.0
```

**Comment by stefanprodan** [comment]
Image automation only works for YAML files which start with `apiVersion` and `kind`.

**Comment by antonosmond** [comment]
Hey @stefanprodan 

Maybe it's unexpected then but it does actually work for generic YAML files too.
In my testing, the entire YAML file I used in a case where it works was:

```yaml
serviceName: busybox
containerName: busybox
tag: 0.0.1 # {"$imagepolicy":"flux-system:busybox:tag"}
```
So it's not a k8s resource but works just fine.
Feel free to try it.

**Comment by errordeveloper** [comment]
@antonosmond I think there is an incidental case, perhaps we can say it happens to recognise resources that have an object at root, perhaps `apiVersion` and `kind` are inferred or something.
I have to say, I find that YAML with an array at the top level is a little unorthodox ;)

**Comment by kimyvgy** [comment]
> Image automation only works for YAML files which start with `apiVersion` and `kind`.

That's why my `patch-image.yaml` file didn't get new container image update. For example:

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:
- path: patch-image.yaml
  target:
    kind: HelmRelease
    name: nginx

# patch-image.yaml
- op: replace
  path: /spec/values/containers/0/image
  value: nginx:alpine
```
