### ISSUE TITLE
`update` field of API is largely empty, and could be optional

### ISSUE THREAD

**Issue by squaremo** [fluxcd/image-automation-controller#66]
The `update` field of the ImageUpdateAutomation spec can only contain one value, since `paths` was removed, and that's `{ setters: {} }`. It isn't defaulted in the schema or in code, so you need to provide

```yaml
# ...
spec:
  update:
    setters: {}
```

which is ugly.

Using `kubebuilder:default` to default it to `{ setters: {} }` doesn't work, because YAML (I think) interprets that inner value as null, and the schema won't accept null.

Assuming we want to keep room for other strategies, a nicer representation might be to use an enum, and (embedded) fields for any parameters:

```yaml
spec:
  update:
    strategy: Setters
    # any strategy parameters go here, either embedded or in an object
```

which means the default value for update can be `{ strategy: "Setters" }`, which is more pleasing.
