### ISSUE TITLE
imagepolicy tag not qouted when tag contains dashes

### ISSUE THREAD

**Issue by gailingmic** [fluxcd/image-automation-controller#713]
Helllo everyone,

when using the image-automation-controller it sets the tag like this for imagetags wich use dashes inside of the tags:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
spec:
  values:
    image:
      repository: ghcr.io/homebridge/homebridge
      tag: 2024-06-27 # {"$imagepolicy": "flux-system:homebridge:tag"}
```

the issue with that is that somewhere down the line it gets interpreted as a dateformat wich means k8s fails to apply the imagetag

```
Failed to apply default image tag "ghcr.io/homebridge/homebridge:2024-06-27T00:00:00Z": couldn't parse image name "ghcr.io/homebridge/homebridge:2024-06-27T00:00:00Z": invalid reference format
```

i think the best fix would be to always qoute the tag as its always of type string.

Sincerely,
Michell
