### ISSUE TITLE
Image Automation not honouring GitRepository exclusions

### ISSUE THREAD

**Issue by jvelasquez** [fluxcd/image-automation-controller#72]
Hi all,

First of all, thanks for the work. 

I am using the latest version of Flux2 and image-automation-controller / reflector. Given the following resources:

```yaml 
---
# Source: environment/templates/env-sync.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: dev-123
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: https://gitlab.com/unodos/gitlab-ci/gitops
  ignore: |
    # exclude all but environment dev-123 patches.yaml
    /*
    !/cluster/environments/dev-123/patches.yaml
---
# Source: environment/templates/patches.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: dev-123
spec:
  values:
    image:
      tag: 5.0.1 # {"$imagepolicy": "flux-system:dev-123-podinfo-policy:tag"}
# Source: environment/templates/image-automations.yaml
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: dev-123-podinfo-automation
  namespace: flux-system
spec:
  interval: 1m
  checkout:
    branch: master
    gitRepositoryRef:
      name: dev-123
  update:
    setters: {}
  commit:
    authorName: UpdateBot
    authorEmail: bot@example.com
```

I am seeing this error: 

```
image-automation-controller-5849df9999-tftj5 manager {"level":"error","ts":"2020-12-21T13:18:30.688Z","logger":"controller","msg":"Reconciler error","reconcilerGroup":"image.toolkit.fluxcd.io","reconcilerKind":"ImageUpdateAutomation","controller":"imageupdateautomation","name":"dev-123-podinfo-automation","namespace":"flux-system","error":"/tmp/flux-system-dev-123935373182/helm/charts/environment/templates/image-automations.yaml: yaml: line 3: did not find expected key"}
```

Note that the path is out of scope for the Gitrepository CRD I have created (only includes `cluster/environments/dev-123/patches.yaml`). Is this an expected behavior? 

Thanks!

**Comment by stefanprodan** [comment]
Related to #68

**Comment by squaremo** [comment]
The image automation uses the git repository type only for its specification of how to gain access to a git repository (i.e., the `url` and `secretRef` fields). It doesn't use other parts of the spec, and in some cases it would be nonsensical to do so -- e.g., what should it make of `ref: {semver: "1.2" }`. In other words, it reuses the type for convenience, but it's not really a great fit.

I can see why you would want it to respect the `ignore` field specifically; it would be handy for excluding things you don't want to be updated (there was a field in the automation object for _including_ paths, but it wasn't implemented, and got removed). I can see some ways it would complicate matters -- if you have several automations working on different parts of the same git repo, it would force you to provide a repo object for each, for instance -- but broadly, useful. However, I am wary of going further in supporting _some_fields of GitRepository while ignoring others.

**Comment by jvelasquez** [comment]
Hi @squaremo, thanks for the comment. 

> The image automation uses the git repository type only for its specification of how to gain access to a git repository (i.e., the url and secretRef fields). It doesn't use other parts of the spec, and in some cases it would be nonsensical to do so -- e.g., what should it make of ref: {semver: "1.2" }. In other words, it reuses the type for convenience, but it's not really a great fit.

Two things I can see here:  
1. I believe that the use of GitRepository in Automation should be then clarified in the documentation -> `The image automation uses the git repository type only for its specification of how to gain access to a git repository (i.e., the url and secretRef fields)` 
2. does not makes sense `ref: {semver: "1.2" }` you are right, but it would `ref: prod` if that is even possible. It is up to the user to f*** things up or not, stating it clear in the docu should suffice. 

> I can see why you would want it to respect the ignore field specifically; it would be handy for excluding things you don't want to be updated (there was a field in the automation object for including paths, but it wasn't implemented, and got removed). I can see some ways it would complicate matters -- if you have several automations working on different parts of the same git repo, it would force you to provide a repo object for each, for instance -- but broadly, useful. However, I am wary of going further in supporting _some_fields of GitRepository while ignoring others.

1. I think adding the GitRepositoryRef, makes the user believe this object will be managed as is in the ImageAutomation resource. Maybe allowing ignore would make sense (would this be such a major change or make the solution more complex?)
```yaml
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: aaa
  namespace: aaa
spec:
  interval: 1m
  checkout:
    branch: dev
    # by default spec.ignore will be blank.
    ignore: |
      /charts
      REDME.md
    gitRepositoryRef:
      name: flux-system
  update:
    setters: {}
  commit:
    authorName: UpdateBot
    authorEmail: bot@example.com
```
