### ISSUE TITLE
Kustomization Images markers should also work for HelmRelease

### ISSUE THREAD

**Issue by nomeelnoj** [fluxcd/image-automation-controller#81]
Hello! Thanks so much for making a more flexible and more secure version--so far it is taking some getting used to, but I am liking what I am seeing!

One issue I am not sure if you are planning for: our workflow is to keep our kustomize manifests in one directory, and then build those into single yaml files that live in another directory, and configure flux v1 to look at that directory.  We have some pretty complex patches and this makes it easy to see exactly what is getting deployed into the cluster.

Because `kustomize` does not keep comments intact when running `kustomize build`, we are having some issues with the image update markers.  We either have to annotate the Kustomization that flux created, or go in after kustomize has built the yaml and modify it there (a pain, especially for some of our automation).  So far, image automation has worked on all `Deployments` because we can define the image policy marker comment in the `Kustomization` object that Flux creates:

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./deploy/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  images:
  - name: someRepo/someImage
    newName: someRepo/someImage
    newTag: 1.0.2 # {"$imagepolicy": "flux-system:test-policy:tag"}
```

However, this does not work for `HelmRelease` objects, which makes sense because often times `image` and `tag` are split up.  An example HelmRelease might be:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-test
spec:
  chart:
    spec:
      chart: charts/nginx
      sourceRef:
        kind: GitRepository
        name: gitops-helm
        namespace: flux-system
      version: 0.1.0
  interval: 5m
  values:
    image:
      repository: someOtherRepo/someOtherImage
      tag: 0.1.0
```

Previously in flux v1, we could just annotate the `HelmRelease` object and call it a day, but since annotation-based image updates are gone, we need to find a way to do it here.  I was hoping that there would be a similar path as above and I could add something like this to the flux `Kustomization` and have it respect the path for any workloads with that image, but they are not getting updated:

```
 images:
  - name: someOtherRepo/someOtherImage
    newName: someOtherRepo/someOtherImage
    newTag: 1.0.2 # {"$imagepolicy": "flux-system:test-policy:image:tag"}
```

I know this is achievable by using a `Kustomization` object and pointing it at the folder that contains the manifests, but that defeats the purpose of having the built file be what is deployed into the cluster.

Is there a solution that would allow us to build our kustomize directories into complete yamls and still get automated image updates? I am really hoping something like this is possible or on the roadmap, because it was quite simple in flux v1.

Thanks!

**Comment by squaremo** [comment]
This is a gnarly one -- but not an unreasonable use case. Let me see if I've understood though:

 - you "pre-bake" your configuration by running kustomize and committing the result (or putting the result in an S3 bin)
 - this would lose the automation markers, because it doesn't preserve comments
 - .. but you can put the markers in the Kustomization sync object, which isn't part of the "pre-bake" process
 - .. but this doesn't work for HelmReleases, which _are_ part of the pre-bake process, because kustomize (and the kustomize controller) don't know how to patch images in HelmRelease values.

You don't have to run the image automation on the same files you are syncing, or even on the same git repo. So you could, for example, run automation on the original files, _then_ produce the bulk YAML to be synced; or, run automation on some intermediate kustomization.yaml that is particular to each environment that shares the config.

It may still be tricky to patch HelmReleases in the same way, if you can't put the markers in them directly. One possibility that comes to mind is to refer to a ConfigMap from the HelmRelease, then build the ConfigMap using kustomize, from files that have the automation markers (phew!).

**Comment by nomeelnoj** [comment]
@squaremo thank you for taking the time to leave a detailed response.  I am still trying to wrap my head around it, despite having read all the docs many times over.

> You don't have to run the image automation on the same files you are syncing, or even on the same git repo.

I am trying to understand this. It sounds like you are saying that the `ImageUpdateAutomation` does not actually care about the `setters`, but applies `ImagePolicy` rules to any resource using that image? That's not right, is it?

Sorry, I am a little lost, and have been staring at this for a while trying to wrap my head around it.  My apologies for the lengthy example, but I want to make sure I fully understand whats going on here.

Right now we do this:

```
$ cat resources/foo/overlays/dev/helmrelease.yaml
# helmrelease.yaml
kind: HelmRelease
...
values:
  image: <myimage>
  tag: 1.2.0  # {"$imagepolicy": "flux-system:foo"}


$ kustomize build resources/foo/overlays/dev > deploy/dev/foo.yaml
$ cat deploy/dev/foo.yaml
# foo.yaml
kind: HelmRelease
...
values:
  image: <myimage>
  tag: 1.2.0 # This setter disappears after running `kustomize build`
```
Check that into the repo and push, flux deploys the helm release because it is already watching the `Kustomization` object that `flux bootstrap` command drops into `deploy/dev/flux-system/gotk-sync.yaml`, and that `Kustomization` is pointing at `deploy/dev`.

Then CI pushes 1.2.1...

I am trying to find a way for us to have flux automatically deploy 1.2.1 to the HelmRelease defined above.

What I think you are saying is that we could create an `ImageUpdateAutomation` resource as follows:
```
$ cat deploy/dev/imageautomation.yaml
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  checkout:
    branch: master
    gitRepositoryRef:
      name: flux-system
  commit:
    authorEmail: fluxcdbot@users.noreply.github.com
    authorName: fluxcdbot
    messageTemplate: '[ci skip] update image'
  interval: 1m0s
  update:
    strategy: setters
```
And somehow that would know which objects to update? If this is the case, then I am confused with the purpose of setters/markers, as this would appear to have the `ImageUpdateAutomation` object just scan the cluster for `ImagePolicies` and update all workloads that use those images.

**Comment by squaremo** [comment]
> I am trying to understand this. It sounds like you are saying that the `ImageUpdateAutomation` does not actually care about the `setters`, but applies `ImagePolicy` rules to any resource using that image? That's not right, is it?

What I meant is that you can use setters on files that are used _earlier_ in your CI/CD process -- they don't have to be the files that you sync.

In your example, you have the marker on a HelmRelease `resources/foo/overlays/dev/helmrelease.yaml`, which is subsequently included in a kustomization in `resources/foo/overlays/dev`. If you (or automation) update the tag in `resources/foo/overlays/dev/helmrelease.yaml`, then `kustomize build resources/foo/overlays/dev` will output the expected, new tag.

```
      update
         +
         |
         v
+--------+---------+                    +---------------------+
|                  |  kustomize build   |                     |
| helmrelease.yaml +------------------->+ deploy/dev/foo.yaml |
|                  |                    |                     |
+------------------+                    +-----------+---------+
                                                    |
                                                    v
                                                  sync

```

**Comment by nomeelnoj** [comment]
Agree about the extra `:tag`, figured that out.

Ok, I think I see what you are saying.  My sincerest apologies, I am still not fully getting it.  The "automation" that I am referring to is the flux image automation component that automatically queries for policies and deploys images.

So what I think you are saying is that we could mark the helm release in `resources/foo/overlays/dev/helmrelease.yaml`, and create a Flux `Kustomization` (apiVersion: kustomize.toolkit.fluxcd.io/v1beta1) object that points to `resources/foo/overlays/dev/helmrelease.yaml`, like this:

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: foo
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./resources/foo/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
```
And flux will deploy and automate images by looking at this directory.

Then, we still can build the resulting complete yaml using `kustomize build resources/foo/overlays/dev`, but we just would not tell flux to look at it, and only have it for our records.

I think the disconnect is that we would like to have one single file that both is up to date with what is most recently deployed in the cluster by flux's image automation, but also that is the result of `kustomize build`.

i want to fully thank you for taking the time to help me through this.  I think it is clear that the recommended path is to just create flux Kustomization objects and point them at the kustomization roots, so I believe we will do something like this (unless you see a flaw in this plan)

1. Tell flux to watch `deploy/dev`
2. Create flux Kustomization objects in `deploy/dev`, e.g. `deploy/dev/foo.yaml` that tell flux to look at `resources/foo/overlays/dev`.  
 
Then we can mark the setters on the master file, and not have to worry about comments disappearing.  If the devs want to see the yaml that is deployed, they can run `kustomize build` and look at it lol.
