### ISSUE TITLE
gcr.io support?

### ISSUE THREAD

**Issue by donnyv12** [fluxcd/image-automation-controller#83]
HI All,

I checked to see if this had been asked, but I am trying to use the below inside a GKE cluster within the same project: 

```yaml
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: hello-world
  namespace: flux-system
spec:
  url: gcr.io/<PROJECT_ID>
  image: hello-world
  interval: 1m0s
```

however when I run `flux get image repository` I get 

```sh
hello-world	False	GET https://gcr.io/v2/<PROJECT_ID>/hello-world/tags/list?n=1000: DENIED: Failed to read tags for host 'gcr.io', repository '/v2/<PROJECT_ID>//hello-world/tags/list?n=1000'
```
I have confirmed that the node service account can pull images, and I've also confirmed that it can list tags for this image using that service account identity. 

I noticed that GCR support is listed as TODO, but I've seen some code snippets that lead me to believe this should work. Any advice? Anything I can do to help? GCR support would be super helpful.
