### ISSUE TITLE
Problem with pushing to refspec

### ISSUE THREAD

**Issue by felixw7k** [fluxcd/image-automation-controller#922]
Hi, 

i think/hope i followed the documentation correctly, but i cannot get pushing to a refspec to work.

i am using:
```
flux: v2.6.1
distribution: flux-v2.6.1
helm-controller: v1.3.0
image-automation-controller: v0.41.0
image-reflector-controller: v0.35.1
kustomize-controller: v1.6.0
notification-controller: v1.6.0
source-controller: v1.6.0
```

My ImageUpdateAutomation (see below) always tries to push into `main` when i have no specific `push.branch`, even if i have `push.refspec` set up. 
Since `main` is a protected branch on my git server (gitea) it results in 
`failed to update source: failed to push to remote: command error on refs/heads/main: pre-receive hook declined`

My goal is to try to use agit and push to `refs/for/main`, but i have also tried `refs/heads/main:refs/heads/auto` (as described in the docs) without success.

i have set up this ImageUpdateAutomation: 
```
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: my-automation
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    push:
      refspec: HEAD:refs/heads/auto
    commit:
      author:
        email: me@example.com
        name: FluxBot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println
        .NewValue}}{{end}}'
  interval: 30m0s
  sourceRef:
    kind: GitRepository
    name: my-repo
  update:
    path: ./kustomize/base/statefulset.yaml
    strategy: Setters
```

Could you provide any hints on what i'm doing wrong? 

Thanks 
 felix

**Comment by stefanprodan** [comment]
The path is wrong, must be a directory instead of a file. Usually you would push to a new branch e.g. `push: flux-updates`, the use same automation to open a PR for merging into main.

**Comment by felixw7k** [comment]
OK, i don't know what i messed up. I created it from scratch and now it works.
For anyone interested: 
This Config opens a PR in gitea/forjeo without the need of a CI/CD-Pipeline:


```
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: my-automation
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    push:
      branch: auto
      refspec: refs/heads/auto:refs/for/main
      options:
        topic: MyPR
    commit:
      author:
        email: me@example.com
        name: FluxBot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println
        .NewValue}}{{end}}'
  interval: 30m0s
  sourceRef:
    kind: GitRepository
    name: my-repo
  update:
    path: ./kustomize/base/statefulset/
    strategy: Setters
```
