### ISSUE TITLE
ImagePolicy stuck on old tag despite cache wipe and controller upgrade (GitLab registry)

### ISSUE THREAD

**Issue by valtrof** [fluxcd/image-automation-controller#927]
### Bug Description

ImagePolicy resource in FluxCD image automation never updates to the latest image tag despite:

- Correct ImageRepository, ImagePolicy, ImageUpdateAutomation manifests (following official docs).
- Image tags present and visible in GitLab Container Registry.
- Full delete and recreate ("nuclear wipe") of all image automation CRs.
- Restart and upgrade of image-reflector-controller and image-automation-controller to latest stable versions.
- Forced reconciliations after all changes.
- Regex filter correctly matching tags (example: '^v[0-9]{8}-[0-9]{6}-[a-f0-9]{8}$').

The latest image tag always stays stuck at an older tag and never switches to newer tags.

### To Reproduce

1. Setup FluxCD image automation with the following YAMLs:

```yaml
# ImageRepository.yaml (relevant parts)
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: micr-asm-asmis
  namespace: flux-system
spec:
  image: registry.gitlab.com/saferentsolutions/saferent/micr-asm-asmis
  interval: 5m
  provider: generic
  secretRef:
    name: flux-image-automation-ssh
```

```yaml
# ImagePolicy.yaml
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: micr-asm-asmis-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: micr-asm-asmis
  filterTags:
    pattern: '^v[0-9]{8}-[0-9]{6}-[a-f0-9]{8}$'
  policy:
    alphabetical:
      order: desc
```

```yaml
# ImageUpdateAutomation.yaml
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: micr-asm-asmis-automation
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: saferent-repo
  git:
    checkout:
      ref:
        branch: fix-deploy-bug
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@example.com
    push:
      branch: fix-deploy-bug
  update:
    strategy: Setters
    path: ./services/micr-asm-asmis/k8s/overlays/cloudflared
```

Use a GitLab Container Registry with image tags matching the pattern above.

Deploy controllers at versions:
- image-automation-controller: v0.41.0
- image-reflector-controller: v0.35.1
- FluxCD CLI version: v2.6.1

Observe that the ImagePolicy latestImage field never updates beyond an older tag despite new tags existing and full cache wipe performed.

Expected behavior
ImagePolicy should update to the newest matching tag, triggering automatic image updates in Kustomization.

Additional context
- Complete delete and recreate of all image automation CRs has no effect.
- Restarting controllers does not fix the issue.
- Registry is GitLab Container Registry.
- Tag format matches official FluxCD docs.
- FluxCD controllers installed via official manifests.
