### ISSUE TITLE
Image-Policy on ConfigMap Literal-Value

### ISSUE THREAD

**Issue by haraldatbmw** [fluxcd/image-automation-controller#96]
I want to use the image-policy replacement mechanism on a literal-value inside my config-map generator of kustomize.

```yaml
configMapGenerator:
- name: frontend
  literals:
  - NGINX_PORT=80
  - APP_VERSION=1.9.0 # {"$imagepolicy": "flux-system:webapp-dev:tag"}
```

The flux-bot makes a wrong replacement like this. The key of the literal gets lost.

```yaml
configMapGenerator:
- name: frontend
  literals:
  - NGINX_PORT=80
  - 1.9.0 # {"$imagepolicy": "flux-system:webapp-dev:tag"}
```

**Comment by squaremo** [comment]
The setter applies to the field, and replaces the field value, so it's working as designed -- but I see why this is not what you want it to do!
If you declared a ConfigMap resource you could put the marker in there:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
data:
  NGINX_PORT: 80
  APP_VERSION: 1.9.0 {"$imagepolicy": "flux-system:webapp-dev:tag"}
```

Of course, there may be reasons you don't want to have it as its own file; and, situations in which the image tag or ref occurs in a larger string (as above) which don't have this workaround. I've posted https://github.com/fluxcd/image-automation-controller/issues/97, describing a feature to cover this situation.

**Comment by haraldatbmw** [comment]
I found an additional workaround by using vars inside in my kustomization.yaml file.
So I can use this var in my base yaml.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: myapp
  newTag: 1.0.0 # {"$imagepolicy": "flux-system:myapp:tag"}
vars:
- name: IMAGE_TAG
  objref:
    kind: Deployment
    name: myapp
    apiVersion: apps/v1
  fieldref:
    fieldpath: spec.template.spec.containers[0].image
```
